### ISSUE TITLE
Error in `config.yaml` settings causes CrashLoopBackOff

### ISSUE THREAD

**Issue by willingc** [odewahn/jupyterhub-on-gcloud#5]
When creating the `config.yaml` file, make sure that `proxy` has a `secretToken` setting.

```
hub:
  cookieSecret: "RANDOM_STRING_1"
proxy:
  secretToken: "RANDOM_STRING_2"
```
Reference: http://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html#prepare-configuration-file

---

This section of the original article has an error in the `config.yaml` which can cause a CrashLoopBackOff state:

<img width="791" alt="screenshot 2017-08-18 05 55 14" src="https://user-images.githubusercontent.com/2680980/29443685-ee2dc8d4-83d9-11e7-93a0-11dafa418940.png">
